# Generated by Django 4.0.2 on 2022-03-08 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bugs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=255)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('on_bug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.bugs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bugs',
            name='classification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.classification'),
        ),
        migrations.AddField(
            model_name='bugs',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creater', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bugs',
            name='users_with',
            field=models.ManyToManyField(related_name='group_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
