# Generated by Django 4.0.2 on 2022-03-09 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugs',
            name='admins',
            field=models.ManyToManyField(related_name='admins_bug', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bugs',
            name='users_with',
            field=models.ManyToManyField(related_name='users_bug', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('admins', models.ManyToManyField(related_name='admins_project', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('users_with', models.ManyToManyField(related_name='users_project', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bugs',
            name='on_project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='project_on', to='backend.project'),
        ),
    ]
